
/**
 * NUMBER GUESSING GAME
 * The fun and easy project “Guess the Number” is a short Java project that allows the
 * user to guess the number generated by the computer & involves the following steps:
 * The system generates a random number from a given range, say 1 to 100.
 * The user is prompted to enter their given number in a displayed dialogue box.
 * The computer then tells if the entered number matches the guesses number or it is
 * higher/lower than the generated number.
 * The game continues under the user guessing the number.
 * You can also incorporate further details as:
 * Limiting the number of attempts.
 * Adding more rounds.
 * Displaying score.
 * Giving points based on the number of attempts.
 */
import java.util.*;

public class guess_number {
    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            int guessNo = new Random().nextInt(100) + 1;
            int attempts = 0, guess = 0;
            System.out.println(" ENTER A NUMBER BETWEEN 1 - 100 ");
            while (guess != guessNo) {
                System.out.print("YOUR GUESS : ");
                guess = sc.nextInt();
                attempts++;
                if (guess < guessNo) {
                    System.out.println("GO HIGHER THAN IT!!!");
                } else if (guess > guessNo) {
                    System.out.println("GO LOWER THAN IT!!!");
                }
            }
            System.out.println("YOU GUESSED IT RIGHT!!. IT TOOK YOU " + attempts + " ATTEMPTS TO GUESS!!");
        }
    }
}